validation script for docker SE added
shotgunsoftware/enterprise-toolbox pull request #8
Opened 2017-06-15 05:49 UTC by sergei-kiktev-autodesk

@guillaume-brossard-adsk 
@david-richer-adsk 
Please check(CentOS 7 only).
Some check can be joined in loop but good as first version.

2017-06-15 18:56 UTC, david-richer-adsk commented on setup/setup_validation_docker.sh
> +#  This scripts is doing basic docket on Centos 7 only  #
docker

2017-06-15 18:57 UTC, david-richer-adsk commented on setup/setup_validation_docker.sh
> +    printf "SE Linux               : %-10s %-10s\n" $OVER `getenforce`
Do we really care about SE Linux with Docker SE?

2017-06-15 18:57 UTC, david-richer-adsk commented
Look great!

2017-06-15 18:57 UTC, david-richer-adsk commented
May be it should validate by default if we run without options?

2017-06-15 21:13 UTC, guillaume-brossard requested changes
Very nice! It will be very useful.

2017-06-15 21:13 UTC, guillaume-brossard-adsk commented on setup/setup_validation_docker.sh
> +esac
No option should default to displaying help.

2017-06-15 21:13 UTC, guillaume-brossard-adsk commented on setup/setup_validation_docker.sh
> +    CPU=`cat /proc/cpuinfo |grep "model name" |awk -F: '{print $2}'| uniq`
Indentation is wrong for CPU Model and Hostname.
```
Kernel version         : OK         3.10
CPU model              : Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
```

I expected:
```
Kernel version         : OK         3.10
CPU model              :                Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
```

2017-06-15 21:13 UTC, guillaume-brossard-adsk commented on setup/setup_validation_docker.sh
> +    STATUS=`systemctl status postgresql.service|grep active|awk '{print $2}'`
In my case, postgresql is running and your script says it is not. Here is how I installed it:
https://docs.google.com/document/d/1OI8s9sFDLoqhc0J_E05-Gu7wEWW3n9Q6bhutZmCaXF4/edit#

2017-06-15 21:13 UTC, guillaume-brossard-adsk commented on setup/setup_validation_docker.sh
> +	sudo cat /var/lib/pgsql/9.*/data/postgresql.conf|grep -E 'shared_buffers|work_mem|maintenance_work_mem|vacuum_cost_delay|effective_cache_size|max_connections|statement_timeout'|uniq
Why not $PG_FILE?

2017-06-15 21:13 UTC, guillaume-brossard-adsk commented on setup/setup_validation_docker.sh
> +	sudo cat /var/lib/pgsql/9.*/data/postgresql.conf|grep -E 'shared_buffers|work_mem|maintenance_work_mem|vacuum_cost_delay|effective_cache_size|max_connections|statement_timeout'|uniq
The `*` doesn't work out for me.

2017-06-19 03:09 UTC, sergei-kiktev-autodesk commented on setup/setup_validation_docker.sh
> +    printf "SE Linux               : %-10s %-10s\n" $OVER `getenforce`
Usually docker comes with additional SELinux policy package and will not work correct if SELinux enabled and package missing. Should we make a note in documentation then?
e.g.:
[shotgun@localhost ~]$ rpm -qa|grep docker
docker-ce-selinux-17.03.1.ce-1.el7.centos.noarch
docker-ce-17.03.1.ce-1.el7.centos.x86_64

2017-06-19 03:40 UTC, sergei-kiktev-autodesk commented on setup/setup_validation_docker.sh
> +    STATUS=`systemctl status postgresql.service|grep active|awk '{print $2}'`
I Could not get installation script from documentation.
Also CentOS 7 is using "systemctl status" command by default.
I also found that postgres is installing to "/var/lib/pgsql/data" by default.

Works on my side.

<img width="593" alt="screen shot 2017-06-19 at 15 39 29" src="https://user-images.githubusercontent.com/13724127/27268707-8c48a024-5505-11e7-991d-6a83f984d6c0.png">

2017-06-19 03:40 UTC, sergei-kiktev-autodesk commented on setup/setup_validation_docker.sh
> +	sudo cat /var/lib/pgsql/9.*/data/postgresql.conf|grep -E 'shared_buffers|work_mem|maintenance_work_mem|vacuum_cost_delay|effective_cache_size|max_connections|statement_timeout'|uniq
Fixed...

2017-06-19 03:40 UTC, sergei-kiktev-autodesk commented on setup/setup_validation_docker.sh
> +	sudo cat /var/lib/pgsql/9.*/data/postgresql.conf|grep -E 'shared_buffers|work_mem|maintenance_work_mem|vacuum_cost_delay|effective_cache_size|max_connections|statement_timeout'|uniq
fixed.

2017-06-19 04:11 UTC, sergei-kiktev-autodesk commented
Fixed. Please review

2017-06-19 17:29 UTC, guillaume-brossard requested changes

2017-06-19 17:29 UTC, guillaume-brossard-adsk commented on setup/setup_validation_docker.sh
> +    printf "SE Linux               : %-10s %-10s\n" $OVER `getenforce`
@david-richer-adsk ?

2017-06-19 17:29 UTC, guillaume-brossard-adsk commented on setup/setup_validation_docker.sh
> +PG_FILE=/var/lib/pgsql/data/postgresql.conf
Default is `/var/lib/pgsql/data/<version>/postgresql.conf` isn't?

2017-06-19 17:29 UTC, guillaume-brossard-adsk commented on setup/setup_validation_docker.sh
> +    STATUS=`systemctl status postgresql.service|grep active|awk '{print $2}'`
Hey Sergei, like I said, this is how we suggest to client to install PostgreSQL. This is the instruction I followed, on a VM, to test your script. So either we need to change the installation script, or make sure the script can detect PostgreSQL running when installed as our script is suggesting.

https://github.com/shotgunsoftware/docker-se/tree/master/postgresql

2017-06-19 17:29 UTC, guillaume-brossard-adsk commented on setup/setup_validation_docker.sh
> +    STATUS=`systemctl status postgresql.service|grep active|awk '{print $2}'`
In my case, the following is working:
`sudo systemctl status postgresql-9.3.service`

2017-06-19 18:25 UTC, david-richer-adsk commented on setup/setup_validation_docker.sh
> +    printf "SE Linux               : %-10s %-10s\n" $OVER `getenforce`
I just don't know if Docker and our containers will work or not.  Let's play safe and require SELinux to be disabled on host like before

2017-06-22 00:48 UTC, sergei-kiktev-autodesk commented on setup/setup_validation_docker.sh
> +    STATUS=`systemctl status postgresql.service|grep active|awk '{print $2}'`
Hm... Weird, default postgres comes with centos repo does not contain version number in /var/lib/pgsql/ and "sudo systemctl status postgresql-9.3.service".

Ok, all good then.

2017-06-22 02:14 UTC, david-richer-adsk commented
Fix postgresql detection tested with postgres 9.3 and 9.6

2017-06-22 14:08 UTC, merged